// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyuuveypceobpxcntccr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dXV2ZXlwY2VvYnB4Y250Y2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjIxMTcsImV4cCI6MjA3NDM5ODExN30.yrD4JHqDf6jR4XRrFR8vLfKUw9TXrJaNCSYUqjZ6fAY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});